import type { ContractorCandidate, TradeCoverage } from "./contractors.ts";
import type { ScopePackage } from "./scope-packages.ts";
export function readyScopePackages(packages: ScopePackage[]) { return packages.filter((item) => item.current_version.status === "ready"); }
export function candidatesForScope(candidates: ContractorCandidate[], scopeId: number) { return candidates.filter((item) => item.scope_package === scopeId); }
export function replaceCandidate(candidates: ContractorCandidate[], updated: ContractorCandidate) { return candidates.map((item) => item.id === updated.id ? updated : item); }
export function canManageContractors(role: string) { return role === "admin" || role === "estimator_operator"; }
export function contractorSourceLabel(candidate: ContractorCandidate) { if (candidate.company.source_type === "internal") return "Internal"; return candidate.company.external_provider === "google_places" ? "External / Google" : "External"; }
export function contractorSearchResultMessage(count: number, partial = false) { if (partial) return `Showing ${count} contractor ${count === 1 ? "result" : "results"}; part of the search area could not be checked.`; if (count === 0) return "No contractor results found within 200 miles of the project"; return `${count} contractor ${count === 1 ? "result" : "results"} found within 200 miles`; }
export type ContractorSort = "best_match" | "internal_first" | "rating" | "review_count" | "company_name";
export function sortContractors(candidates: ContractorCandidate[], sort: ContractorSort) { return [...candidates].sort((left, right) => { if (sort === "internal_first") { const source = Number(right.company.source_type === "internal") - Number(left.company.source_type === "internal"); if (source) return source; } if (sort === "rating") { const rating = (right.google_rating ?? -1) - (left.google_rating ?? -1); if (rating) return rating; } if (sort === "review_count") { const reviews = (right.google_review_count ?? -1) - (left.google_review_count ?? -1); if (reviews) return reviews; } if (sort !== "company_name") { const score = right.match_score - left.match_score; if (score) return score; } const name = left.company.display_name.localeCompare(right.company.display_name); return name || left.id - right.id; }); }
export function contractorFitBand(score: number) { if (score >= 80) return "Excellent fit"; if (score >= 65) return "Good fit"; return "Possible fit"; }
export function contractorRankingSignals(candidate: ContractorCandidate) { return candidate.match_reasons.map((reason) => { if (reason === "Internal network") return "Internal BB network"; if (reason.includes("Google rating") && candidate.google_rating !== null) return `Google rating ${candidate.google_rating.toFixed(1)}`; if (reason === "Established review history" && candidate.google_review_count !== null) return `${candidate.google_review_count} reviews`; return reason; }); }
export function contractorShortlistPresentation(status: ContractorCandidate["status"], canManage: boolean) { if (status === "shortlisted") return { kind: "status" as const, label: "Shortlisted ✓" }; if (status === "candidate" && canManage) return { kind: "action" as const, label: "Add to Shortlist" }; if (status === "candidate") return null; return { kind: "status" as const, label: status.replaceAll("_", " ") }; }
export function filterContractors(candidates: ContractorCandidate[], shortlistedOnly: boolean) { return shortlistedOnly ? candidates.filter((candidate) => candidate.status === "shortlisted") : candidates; }
export function tradeCoverage(packages: ScopePackage[], candidates: ContractorCandidate[], minimumTarget: number): TradeCoverage[] { return readyScopePackages(packages).map((scope) => { const rows = candidatesForScope(candidates, scope.id); const activeCandidates = rows.filter((candidate) => candidate.status !== "rejected"); const shortlistedCount = rows.filter((candidate) => candidate.status === "shortlisted").length; return { scope_package: scope.id, scope_version: scope.current_version.version, trade_key: scope.trade_key, trade_category: scope.trade_category, title: scope.current_version.title, candidates_found: activeCandidates.length, shortlisted_count: shortlistedCount, coverage_status: shortlistedCount >= minimumTarget ? "ready" : "needs_more_candidates" }; }); }
