import { apiRequest, apiResponse } from "@/lib/api-client";

export type ProspectRole = "admin" | "estimator_operator" | "viewer";
export type ProspectListSummary = { id: number; name: string; description: string; status: "active" | "archived"; prospect_count: number; contact_ready_count: number; created_at: string; updated_at: string };
export type ProspectContact = { id: number; name: string; title: string; email: string; phone: string; is_primary: boolean; is_active: boolean };
export type ProspectEntry = { id: number; company: { id: number; display_name: string; website: string; phone: string; email: string; city: string; province: string; country: string; source_type: string; trades: { trade_key: string; trade_label: string }[]; contacts: ProspectContact[] }; primary_contact: ProspectContact | null; status: "new" | "reviewing" | "contact_ready" | "not_a_fit" | "suppressed"; source_type: string; source_reference: string; source_url: string; notes: string; tags: { id: number; name: string }[]; added_at: string; updated_at: string };
export type DiscoveryResult = { id: number; display_name: string; website: string; phone: string; address: string; city: string; province: string; postal_code: string; country: string; source_url: string; provider_metadata: { rating?: number; review_count?: number }; already_in_directory: boolean; already_on_selected_list: boolean };
export type ContactSuggestion = { name: string; title: string; email: string; phone: string; is_primary: boolean; is_active: boolean; sources: { label: string; url: string; fields: string[] }[] };
export type ProspectCampaignSummary = { id: number; name: string; status: "draft" | "approved" | "active" | "paused" | "completed" | "archived"; recipient_count: number; step_count: number; approved_at: string | null; launched_at: string | null; updated_at: string };
export type ProspectMetrics = { enrolled: number; eligible: number; suppressed: number; sent: number; delivered: number; opened: number; clicked: number; replied: number; bounced: number; complained: number; unsubscribed: number; failed: number; active: number; completed: number; rates: Record<string, number | null> };
export type AnalyticsRange = "7d" | "30d" | "90d" | "all";
export type AnalyticsMetrics = { prospects_contacted: number; messages_sent: number; delivered: number; opened: number; clicked: number; replied: number; bounced: number; complained: number; unsubscribed: number; rates: { delivery: number | null; open: number | null; click: number | null; reply: number | null; bounce: number | null; unsubscribe: number | null }; tracking: { available: boolean; event_count: number; message: string } };
export type AnalyticsCampaign = AnalyticsMetrics & { id: number; name: string; status: string; launched_at: string | null; created_at: string; last_activity: string | null; enrolled: number; active: number; completed: number; cancelled: number; step_count: number };
export type AnalyticsRecipient = { id: number; name: string; company: string; email: string; campaign: { id: number; name: string }; step: number | null; sent_at: string | null; delivered_at: string | null; first_opened_at: string | null; last_opened_at: string | null; open_count: number; first_clicked_at: string | null; click_count: number; replied_at: string | null; state: string; flags: Record<string, boolean> };
export type ProspectSequenceStep = { id: number; step_number: number; label: string; subject: string; body: string; delay_minutes: number; enabled: boolean };
export type ProspectEmailTemplate = { id: number; name: string; category: string; subject: string; body: string; is_active: boolean; created_at: string; updated_at: string };
export type ProspectPreview = { from_name: string; from_address: string; reply_to: string; to_name: string; to_address: string; subject: string; body: string; business_identity: string; compliance_footer: string; unsubscribe: string };
export type ManualProspectInput = { name: string; email: string; phone?: string; company?: string; trade?: string; tags?: string[]; notes?: string };
export type ProspectImportPreview = { import: { id: number; filename: string; status: string; total_rows: number; valid_rows: number; warning_rows: number; error_rows: number; imported_rows: number; skipped_rows: number }; summary: { total_rows: number; valid_rows: number; warning_rows: number; invalid_rows: number; likely_duplicates: number; existing_companies: number; existing_contacts: number; valid_contact_email: number; missing_contact_email: number }; rows: { row_number: number; status: "valid" | "warning" | "invalid"; importable: boolean; errors: string[]; warnings: string[]; existing_company_id: number | null; existing_contact_id: number | null; values: { company_name: string; city: string; province: string; trade_original: string; contact_name: string; contact_email: string } }[] };

const root = (slug: string) => `/organizations/${encodeURIComponent(slug)}/prospecting`;
export const prospectingApi = {
  summary(slug: string) { return apiRequest<{ total_prospects: number; contact_ready: number; needs_contact: number; lists: number; recent_discovery: { id: number; trade_label: string; query: string; location: string; provider: string; result_count: number; requested_at: string }[] }>(`${root(slug)}/summary/`); },
  lists(slug: string, query = new URLSearchParams()) { const suffix = query.toString(); return apiRequest<{ count: number; next: string | null; previous: string | null; results: ProspectListSummary[]; can_manage: boolean }>(`${root(slug)}/lists/${suffix ? `?${suffix}` : ""}`); },
  createList(slug: string, values: { name: string; description: string }) { return apiRequest<ProspectListSummary>(`${root(slug)}/lists/`, { method: "POST", body: JSON.stringify(values) }); },
  listDetail(slug: string, id: number, query = new URLSearchParams()) { const suffix = query.toString(); return apiRequest<{ list: Pick<ProspectListSummary, "id" | "name" | "description" | "status" | "updated_at">; can_manage: boolean; count: number; next: string | null; previous: string | null; page: number; results: ProspectEntry[] }>(`${root(slug)}/lists/${id}/${suffix ? `?${suffix}` : ""}`); },
  setListStatus(slug: string, id: number, status: "active" | "archived") { return apiRequest(`${root(slug)}/lists/${id}/`, { method: "PATCH", body: JSON.stringify({ status }) }); },
  companyOptions(slug: string, search = "") { const query = search ? `?search=${encodeURIComponent(search)}` : ""; return apiRequest<{ trades: { value: string; label: string }[]; results: { id: number; name: string; city: string; province: string }[] }>(`${root(slug)}/company-options/${query}`); },
  addManualProspect(slug: string, listId: number, values: ManualProspectInput) { return apiRequest<{ created: boolean; entry: ProspectEntry }>(`${root(slug)}/lists/${listId}/prospects/manual/`, { method: "POST", body: JSON.stringify(values) }); },
  previewImport(slug: string, listId: number, file: File) { const body = new FormData(); body.append("file", file); return apiRequest<ProspectImportPreview>(`${root(slug)}/lists/${listId}/imports/`, { method: "POST", body }); },
  confirmImport(slug: string, listId: number, importId: number) { return apiRequest<{ import: ProspectImportPreview["import"] }>(`${root(slug)}/lists/${listId}/imports/${importId}/confirm/`, { method: "POST", body: "{}" }); },
  downloadImportTemplate(slug: string) { return apiResponse(`${root(slug)}/import-template/`).then((response) => response.blob()); },
  discoveryOptions(slug: string) { return apiRequest<{ trades: { value: string; label: string }[]; results: unknown[] }>(`${root(slug)}/discoveries/`); },
  discover(slug: string, values: { trade_key: string; query: string; keywords: string[]; city: string; province: string; country: string; radius_miles: number; prospect_list_id?: number }) { return apiRequest<{ id: number; provider: string; result_count: number; results: DiscoveryResult[] }>(`${root(slug)}/discoveries/`, { method: "POST", body: JSON.stringify(values) }); },
  addResults(slug: string, runId: number, listId: number, resultIds: number[]) { return apiRequest<{ added_count: number; entry_ids: number[] }>(`${root(slug)}/discoveries/${runId}/add/`, { method: "POST", body: JSON.stringify({ prospect_list_id: listId, result_ids: resultIds }) }); },
  updateEntry(slug: string, id: number, values: { status?: ProspectEntry["status"]; notes?: string; tags?: string[]; primary_contact_id?: number }) { return apiRequest<ProspectEntry>(`${root(slug)}/entries/${id}/`, { method: "PATCH", body: JSON.stringify(values) }); },
  async removeEntry(slug: string, id: number) { await apiResponse(`${root(slug)}/entries/${id}/`, { method: "DELETE" }); },
  enrich(slug: string, id: number) { return apiRequest<{ suggestions: ContactSuggestion[]; pages_checked: string[] }>(`${root(slug)}/entries/${id}/enrichment/`, { method: "POST", body: "{}" }); },
  saveContact(slug: string, id: number, suggestion: ContactSuggestion) { return apiRequest<{ contact: ProspectContact; entry: ProspectEntry }>(`${root(slug)}/entries/${id}/contacts/`, { method: "POST", body: JSON.stringify({ name: suggestion.name, title: suggestion.title, email: suggestion.email, phone: suggestion.phone, is_primary: true, is_active: true }) }); },
  campaigns(slug: string, status: "active" | "archived" = "active") { const query = status === "archived" ? "?status=archived" : ""; return apiRequest<{ count: number; results: ProspectCampaignSummary[]; can_manage: boolean; can_admin: boolean }>(`${root(slug)}/campaigns/${query}`); },
  createCampaign(slug: string, values: { name: string; list_ids: number[] }) { return apiRequest<ProspectCampaignSummary>(`${root(slug)}/campaigns/`, { method: "POST", body: JSON.stringify(values) }); },
  campaign(slug: string, id: number) { return apiRequest<{ campaign: ProspectCampaignSummary & { source_list_ids: number[] }; steps: ProspectSequenceStep[]; readiness: { ready: boolean; blockers: string[]; eligible_recipients: number }; metrics: ProspectMetrics; recipients: { id: number; company_name: string; contact_name: string; normalized_email: string; state: string; current_step: number; next_due_at: string | null; last_sent_at: string | null; stop_reason: string }[]; can_manage: boolean; can_admin: boolean }>(`${root(slug)}/campaigns/${id}/`); },
  saveStep(slug: string, campaignId: number, values: Omit<ProspectSequenceStep, "id">, stepId?: number) { return apiRequest<ProspectSequenceStep>(`${root(slug)}/campaigns/${campaignId}/steps/${stepId ? `${stepId}/` : ""}`, { method: "POST", body: JSON.stringify(values) }); },
  async removeStep(slug: string, campaignId: number, stepId: number) { await apiResponse(`${root(slug)}/campaigns/${campaignId}/steps/${stepId}/`, { method: "DELETE" }); },
  reorderSteps(slug: string, campaignId: number, orderedStepIds: number[]) { return apiRequest<ProspectSequenceStep[]>(`${root(slug)}/campaigns/${campaignId}/sequence/reorder/`, { method: "POST", body: JSON.stringify({ ordered_step_ids: orderedStepIds }) }); },
  duplicateStep(slug: string, campaignId: number, stepId: number) { return apiRequest<ProspectSequenceStep>(`${root(slug)}/campaigns/${campaignId}/sequence/duplicate/`, { method: "POST", body: JSON.stringify({ step_id: stepId }) }); },
  previewCampaignStep(slug: string, campaignId: number, stepId: number, recipientId: number) { return apiRequest<ProspectPreview>(`${root(slug)}/campaigns/${campaignId}/preview/`, { method: "POST", body: JSON.stringify({ step_id: stepId, recipient_id: recipientId }) }); },
  sendTestEmail(slug: string, campaignId: number, values: { step_id: number; recipient_id?: number; test_email: string }) { return apiRequest<{ detail: string }>(`${root(slug)}/campaigns/${campaignId}/test-email/`, { method: "POST", body: JSON.stringify(values) }); },
  templates(slug: string, status: "active" | "archived" = "active") { return apiRequest<{ results: ProspectEmailTemplate[] }>(`${root(slug)}/templates/?status=${status}`); },
  createTemplate(slug: string, values: { name: string; category?: string; subject: string; body: string }) { return apiRequest<ProspectEmailTemplate>(`${root(slug)}/templates/`, { method: "POST", body: JSON.stringify(values) }); },
  updateTemplate(slug: string, id: number, values: Partial<Pick<ProspectEmailTemplate, "name" | "category" | "subject" | "body" | "is_active">>) { return apiRequest<ProspectEmailTemplate>(`${root(slug)}/templates/${id}/`, { method: "PATCH", body: JSON.stringify(values) }); },
  enroll(slug: string, campaignId: number, values: { list_ids?: number[]; entry_ids?: number[]; preview?: boolean }) { return apiRequest<{ selected: number; contact_ready: number; duplicates: number; suppressed: number; invalid: number; eligible: number; recipient_ids?: number[] }>(`${root(slug)}/campaigns/${campaignId}/recipients/`, { method: "POST", body: JSON.stringify(values) }); },
  campaignAction(slug: string, campaignId: number, action: "approve" | "launch" | "pause" | "resume" | "archive" | "restore") { return apiRequest(`${root(slug)}/campaigns/${campaignId}/${action}/`, { method: "POST", body: "{}" }); },
  removeCampaign(slug: string, campaignId: number) { return apiRequest<{ outcome: "deleted" | "archived"; detail: string }>(`${root(slug)}/campaigns/${campaignId}/`, { method: "DELETE" }); },
  cancelRecipient(slug: string, recipientId: number) { return apiRequest(`${root(slug)}/recipients/${recipientId}/cancel/`, { method: "POST", body: "{}" }); },
  suppressions(slug: string) { return apiRequest<{ count: number; results: { id: number; email: string; reason: string; active: boolean; created_at: string }[]; can_admin: boolean }>(`${root(slug)}/suppressions/`); },
  suppress(slug: string, email: string) { return apiRequest(`${root(slug)}/suppressions/`, { method: "POST", body: JSON.stringify({ email }) }); },
  unsuppress(slug: string, id: number) { return apiRequest(`${root(slug)}/suppressions/${id}/remove/`, { method: "POST", body: "{}" }); },
  analytics(slug: string, range: AnalyticsRange) { return apiRequest<{ range: AnalyticsRange; summary: AnalyticsMetrics; trend: { date: string; sent: number; delivered: number; opened: number; replied: number }[] }>(`${root(slug)}/analytics/?range=${range}`); },
  analyticsCampaigns(slug: string, range: AnalyticsRange, sort: string) { return apiRequest<{ count: number; next: string | null; previous: string | null; results: AnalyticsCampaign[] }>(`${root(slug)}/analytics/campaigns/?range=${range}&sort=${encodeURIComponent(sort)}`); },
  analyticsCampaign(slug: string, id: number, range: AnalyticsRange) { return apiRequest<{ range: AnalyticsRange; campaign: AnalyticsCampaign; steps: { id: number; step_number: number; label: string; sent: number; delivered: number; opened: number; clicked: number; replied: number; bounced: number; complained: number }[] }>(`${root(slug)}/analytics/campaigns/${id}/?range=${range}`); },
  analyticsRecipients(slug: string, query: URLSearchParams) { return apiRequest<{ count: number; next: string | null; previous: string | null; results: AnalyticsRecipient[] }>(`${root(slug)}/analytics/recipients/?${query.toString()}`); },
  analyticsRecipient(slug: string, id: number) { return apiRequest<{ recipient: { id: number; name: string; company: string; email: string; campaign: { id: number; name: string }; state: string; current_step: number; next_due_at: string | null; reply_state: string; suppression: string | null; unsubscribed: boolean }; timeline: { at: string; type: string; label: string }[] }>(`${root(slug)}/analytics/recipients/${id}/`); },
  settings(slug: string) { return apiRequest<Record<string, unknown> & { is_enabled: boolean; max_sends_per_hour: number; max_sends_per_day: number; sending_timezone: string; allowed_start_hour: number; allowed_end_hour: number; business_identity: string; compliance_footer: string; sender_configured: boolean; can_admin: boolean }>(`${root(slug)}/settings/`); },
  saveSettings(slug: string, values: Record<string, unknown>) { return apiRequest(`${root(slug)}/settings/`, { method: "PATCH", body: JSON.stringify(values) }); },
    processDue(slug: string) { return apiRequest<{ processed: number; sent: number; scheduled: number; skipped: number; failed: number }>(`${root(slug)}/process-due/`, { method: "POST", body: "{}" }); },
  publicUnsubscribe(token: string, submit = false) { return apiRequest<{ state: string }>(`/prospecting/unsubscribe/${encodeURIComponent(token)}/`, submit ? { method: "POST", body: "{}" } : undefined); },
};
