# Generated by Django 5.2.17 on 2026-09-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='organizations.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estimate', to='projects.project')),
            ],
            options={
                'ordering': ('project_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EstimateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_versions', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='proposals.estimate')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='proposals.estimateversion')),
            ],
            options={
                'ordering': ('estimate_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='projects.projectcontact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='proposals.estimate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='organizations.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='projects.project')),
            ],
            options={
                'ordering': ('project_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposal_versions', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_versions', to='proposals.estimateversion')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='proposals.proposal')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='proposals.proposalversion')),
            ],
            options={
                'ordering': ('proposal_id', 'version'),
            },
        ),
        migrations.AddConstraint(
            model_name='estimateversion',
            constraint=models.UniqueConstraint(fields=('estimate', 'version'), name='unique_estimate_version_number'),
        ),
        migrations.AddConstraint(
            model_name='estimateversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='estimate_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='unique_proposal_version_number'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='proposal_version_positive'),
        ),
    ]
