# Generated by Django 5.2.17 on 2026-09-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        ('outreach', '0016_bid_human_review'),
        ('projects', '0001_initial'),
        ('proposals', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('treatment', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded')], max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_allowances', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances', to='proposals.estimateversion')),
                ('source_bid_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidrevision')),
                ('source_commercial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcommercialitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimate_allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('estimate_version', 'sequence'), name='unique_estimate_allowance_sequence'), models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='estimate_allowance_amount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='EstimateAlternate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('direction', models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('included_in_estimate', models.BooleanField(default=False)),
                ('source_included_in_base', models.BooleanField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_alternates', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternates', to='proposals.estimateversion')),
                ('source_bid_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidrevision')),
                ('source_commercial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcommercialitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimate_alternates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('estimate_version', 'sequence'), name='unique_estimate_alternate_sequence'), models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='estimate_alternate_amount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='EstimateExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_exclusions', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusions', to='proposals.estimateversion')),
                ('source_bid_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidrevision')),
                ('source_commercial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcommercialitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimate_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('estimate_version', 'sequence'), name='unique_estimate_exclusion_sequence')],
            },
        ),
        migrations.CreateModel(
            name='EstimateFinancialAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('markup', 'Markup'), ('overhead', 'Overhead'), ('profit', 'Profit'), ('contingency', 'Contingency'), ('tax', 'Tax'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('fixed_amount', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20)),
                ('basis', models.CharField(choices=[('direct_cost', 'Normalized direct cost'), ('running_subtotal', 'Running subtotal'), ('pre_tax_subtotal', 'Pre-tax subtotal')], max_length=30)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_financial_adjustments', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='proposals.estimateversion')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_estimate_financial_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('estimate_version', 'sequence'), name='unique_estimate_adjustment_sequence'), models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='estimate_adjustment_fixed_nonnegative'), models.CheckConstraint(condition=models.Q(('percentage_rate__isnull', True), ('percentage_rate__gte', 0), _connector='OR'), name='estimate_adjustment_rate_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('source_base_bid', 'Selected contractor base bid'), ('m3_leveling', 'BB Builders bid-leveling adjustment')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('direction', models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct')], default='add', max_length=10)),
                ('included', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField()),
                ('company_name_snapshot', models.CharField(max_length=255)),
                ('trade_snapshot', models.CharField(max_length=255)),
                ('source_category_snapshot', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimate_lines', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_lines', to='proposals.estimateversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('source_bid_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='outreach.bidrevision')),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='contractors.company')),
                ('source_comparison_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='outreach.bidcomparisonentry')),
                ('source_human_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='outreach.bidhumanreview')),
                ('source_leveling_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='outreach.bidlevelingadjustment')),
                ('source_scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_lines', to='scope_packages.scopepackageversion')),
            ],
            options={
                'ordering': ('sequence', 'id'),
                'constraints': [models.UniqueConstraint(fields=('estimate_version', 'sequence'), name='unique_estimate_line_sequence'), models.UniqueConstraint(condition=models.Q(('line_type', 'source_base_bid')), fields=('estimate_version', 'source_human_review'), name='unique_estimate_selected_review'), models.UniqueConstraint(condition=models.Q(('source_leveling_adjustment__isnull', False)), fields=('estimate_version', 'source_leveling_adjustment'), name='unique_estimate_leveling_source'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='estimate_line_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='estimate_line_sequence_positive')],
            },
        ),
    ]
