# Generated by Django 5.2.17 on 2026-09-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_projectdocumentselection'),
        ('projects', '0001_initial'),
        ('proposals', '0002_estimateallowance_estimatealternate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateversion',
            name='calculation_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_estimate_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_versions', to='projects.projectcontact'),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='client_project_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='commercial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='finalization_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_proposal_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='proposal_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='scope_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='snapshot_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estimateversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Frozen')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposalPdfArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.CharField(max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_pdf_artifact', to='documents.fileasset')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_proposal_pdfs', to=settings.AUTH_USER_MODEL)),
                ('proposal_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_artifact', to='proposals.proposalversion')),
            ],
            options={
                'ordering': ('-generated_at', '-id'),
            },
        ),
    ]
