# Generated by Django 5.2.17 on 2026-09-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_projectdocumentselection'),
        ('proposals', '0003_estimateversion_calculation_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalpdfartifact',
            options={'ordering': ('-version', '-id')},
        ),
        migrations.AddField(
            model_name='proposalpdfartifact',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposalpdfartifact',
            name='proposal_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_artifacts', to='proposals.proposalversion'),
        ),
        migrations.AddConstraint(
            model_name='proposalpdfartifact',
            constraint=models.UniqueConstraint(fields=('proposal_version', 'version'), name='unique_proposal_pdf_artifact_version'),
        ),
    ]
