# Generated by Django 5.2.17 on 2026-09-19 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('documents', '0005_projectdocumentselection'),
        ('organizations', '0001_initial'),
        ('outreach', '0016_bid_human_review'),
        ('projects', '0001_initial'),
        ('proposals', '0004_version_proposal_pdf_artifacts'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('award_date', models.DateField()),
                ('rationale', models.TextField()),
                ('client_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.fileasset')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_project_awards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_awards', to=settings.AUTH_USER_MODEL)),
                ('estimate_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_awards', to='proposals.estimateversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_awards', to='projects.project')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_awards', to='proposals.proposalversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='proposals.projectaward')),
            ],
            options={
                'ordering': ('-sequence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AwardedProjectHandoffSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_award_handoffs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_handoffs', to='projects.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='proposals.awardedprojecthandoffsnapshot')),
                ('project_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs', to='proposals.projectaward')),
            ],
            options={
                'ordering': ('-sequence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TradeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('quoted_base_bid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('evaluated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('award_date', models.DateField()),
                ('rationale', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('bid_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidrevision')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.company')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcomparison')),
                ('comparison_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcomparisonentry')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_trade_awards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trade_awards', to=settings.AUTH_USER_MODEL)),
                ('human_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidhumanreview')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_awards', to='projects.project')),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='proposals.tradeaward')),
            ],
            options={
                'ordering': ('scope_package_id', '-sequence', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='projectaward',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_project_award_sequence'),
        ),
        migrations.AddConstraint(
            model_name='awardedprojecthandoffsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_award_handoff_sequence'),
        ),
        migrations.AddConstraint(
            model_name='awardedprojecthandoffsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='unique_award_handoff_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='tradeaward',
            constraint=models.UniqueConstraint(fields=('project', 'scope_package', 'sequence'), name='unique_trade_award_sequence'),
        ),
    ]
