# Generated by Django 5.2.17 on 2026-08-31 21:51

import decimal

import apps.organizations.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('documents_uploaded', 'Documents Uploaded'), ('ai_analysis', 'AI Analysis'), ('human_scope_review', 'Human Scope Review'), ('trade_packages_ready', 'Trade Packages Ready'), ('contractor_discovery', 'Contractor Discovery'), ('outreach_active', 'Outreach Active'), ('bid_collection', 'Bid Collection'), ('bid_leveling', 'Bid Leveling'), ('human_award_review', 'Human Award Review'), ('final_proposal', 'Final Proposal'), ('awarded', 'Awarded')], default='draft', max_length=40)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('site_address_line_1', models.CharField(blank=True, max_length=255)),
                ('site_address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province_state', models.CharField(blank=True, max_length=120)),
                ('postal_zip_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('project_timezone', models.CharField(max_length=64, validators=[apps.organizations.models.validate_timezone])),
                ('project_type', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('office', 'Office'), ('commercial', 'Commercial'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('estimated_area', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('area_unit', models.CharField(choices=[('sf', 'Square feet'), ('m2', 'Square metres')], default='sf', max_length=10)),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('questions_deadline', models.DateTimeField(blank=True, null=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('substantial_completion_date', models.DateField(blank=True, null=True)),
                ('opening_or_handover_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization')),
            ],
            options={
                'ordering': ('-updated_at', 'project_number'),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='projects.project')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_role', models.CharField(choices=[('client', 'Client'), ('architect', 'Architect'), ('consultant', 'Consultant'), ('landlord', 'Landlord'), ('project_manager', 'Project Manager'), ('bid_contact', 'Bid Contact'), ('site_contact', 'Site Contact'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='projects.project')),
            ],
            options={
                'ordering': ('contact_role', 'company_name', 'person_name', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('project_number'), models.F('organization'), name='unique_project_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_area__isnull', True), ('estimated_area__gt', 0), _connector='OR'), name='project_estimated_area_positive'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='projects_au_organiz_1a0a20_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['project', 'occurred_at'], name='projects_au_project_2edff2_idx'),
        ),
    ]
