# Generated by Django 5.2.17 on 2026-10-08 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectingDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('trade_key', models.CharField(choices=[('av', 'AV'), ('backing-blocking', 'Backing / Blocking'), ('civil-site', 'Civil / Site Work'), ('closeout', 'Closeout'), ('demolition', 'Demolition'), ('doors-frames-hardware', 'Doors / Frames / Hardware'), ('drywall', 'Drywall'), ('electrical-power', 'Electrical Power'), ('fire-alarm', 'Fire Alarm'), ('fire-protection', 'Fire Protection / Sprinklers'), ('flooring', 'Flooring'), ('glazing-storefront', 'Glazing / Storefront'), ('hvac-mechanical', 'HVAC / Mechanical'), ('lighting', 'Lighting'), ('low-voltage-data', 'Low Voltage / Data'), ('millwork', 'Millwork'), ('miscellaneous-metals', 'Miscellaneous Metals'), ('mudding-taping', 'Mudding & Taping'), ('painting-finishes', 'Painting / Finishes'), ('plumbing', 'Plumbing'), ('roofing', 'Roofing'), ('security', 'Security'), ('signage', 'Signage'), ('specialties', 'Specialties'), ('steel-stud-framing', 'Steel Stud Framing'), ('structural', 'Structural'), ('act-ceilings', 'T-Bar / ACT Ceilings')], max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('radius_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.CharField(max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_discovery_runs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_discovery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prospect_lists', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_lists', to='organizations.organization')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contact_ready', 'Contact ready'), ('not_a_fit', 'Not a fit'), ('suppressed', 'Suppressed')], default='new', max_length=24)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_prospects', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_entries', to='contractors.company')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_prospect_entries', to='contractors.contact')),
                ('prospect_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='prospecting.prospectlist')),
            ],
            options={
                'ordering': ('company__display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_tags', to='organizations.organization')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectListEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospecting.prospectlistentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prospecting.prospecttag')),
            ],
        ),
        migrations.AddField(
            model_name='prospectlistentry',
            name='tags',
            field=models.ManyToManyField(blank=True, through='prospecting.ProspectListEntryTag', to='prospecting.prospecttag'),
        ),
        migrations.CreateModel(
            name='ProspectingDiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('external_place_id', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_discovery_results', to='contractors.company')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='prospecting.prospectingdiscoveryrun')),
            ],
            options={
                'ordering': ('display_name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('run', 'external_place_id'), name='prospecting_unique_run_provider_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='prospectlist',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='prospecting_unique_list_name'),
        ),
        migrations.AddConstraint(
            model_name='prospecttag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='prospecting_unique_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='prospectlistentrytag',
            constraint=models.UniqueConstraint(fields=('entry', 'tag'), name='prospecting_unique_entry_tag'),
        ),
        migrations.AddConstraint(
            model_name='prospectlistentry',
            constraint=models.UniqueConstraint(fields=('prospect_list', 'company'), name='prospecting_unique_list_company'),
        ),
    ]
