# Generated by Django 5.2.17 on 2026-10-08 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        ('outreach', '0016_bid_human_review'),
        ('prospecting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_prospect_campaigns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prospect_campaigns', to=settings.AUTH_USER_MODEL)),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='launched_prospect_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_campaigns', to='organizations.organization')),
                ('source_lists', models.ManyToManyField(blank=True, related_name='campaigns', to='prospecting.prospectlist')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectCampaignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('sender_name', models.CharField(max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('business_identity', models.CharField(max_length=255)),
                ('compliance_footer', models.TextField()),
                ('sequence_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='prospecting.prospectcampaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_title', models.CharField(blank=True, max_length=255)),
                ('normalized_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('replied', 'Replied'), ('completed', 'Completed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('suppressed', 'Suppressed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=255)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='prospecting.prospectcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.contact')),
                ('enrolled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prospect_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_enrollments', to='prospecting.prospectlistentry')),
                ('campaign_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='prospecting.prospectcampaignversion')),
            ],
            options={
                'ordering': ('company_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('max_sends_per_hour', models.PositiveIntegerField(default=20)),
                ('max_sends_per_day', models.PositiveIntegerField(default=100)),
                ('sending_timezone', models.CharField(default='America/Toronto', max_length=64)),
                ('allowed_start_hour', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('allowed_end_hour', models.PositiveSmallIntegerField(default=17, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('business_identity', models.CharField(blank=True, max_length=255)),
                ('compliance_footer', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('unsubscribe_url', models.URLField(max_length=500)),
                ('rfc_message_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='prospecting.prospectcampaignrecipient')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('provider_key', models.CharField(max_length=40)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('rfc_message_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('uncertain', 'Outcome uncertain')], default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('safe_error_message', models.CharField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='prospecting.prospectmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectProviderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_email_id', models.CharField(max_length=120)),
                ('rfc_message_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prospecting.prospectmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('provider_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.resendwebhookevent')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('in_reply_to', models.CharField(max_length=255)),
                ('references', models.CharField(blank=True, max_length=1000)),
                ('received_at', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prospecting.prospectmessage')),
                ('provider_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_reply', to='outreach.resendwebhookevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='prospecting.prospectcampaignrecipient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProspectSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='prospecting.prospectcampaign')),
            ],
            options={
                'ordering': ('step_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectSequenceStepVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('delay_minutes', models.PositiveIntegerField()),
                ('campaign_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='prospecting.prospectcampaignversion')),
            ],
            options={
                'ordering': ('step_number', 'id'),
            },
        ),
        migrations.AddField(
            model_name='prospectmessage',
            name='step_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='prospecting.prospectsequencestepversion'),
        ),
        migrations.CreateModel(
            name='ProspectSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('unsubscribe', 'Unsubscribe'), ('hard_bounce', 'Hard bounce'), ('complaint', 'Complaint'), ('manual', 'Manual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_suppressions', to='organizations.organization')),
                ('provider_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.resendwebhookevent')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_prospect_suppressions', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prospecting.prospectmessage')),
                ('source_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prospecting.prospectcampaignrecipient')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProspectUnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unsubscribe_tokens', to='prospecting.prospectcampaignrecipient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prospectcampaign',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='prospecting_unique_campaign_name'),
        ),
        migrations.AddConstraint(
            model_name='prospectcampaignversion',
            constraint=models.UniqueConstraint(fields=('campaign', 'version_number'), name='prospecting_unique_campaign_version'),
        ),
        migrations.AddConstraint(
            model_name='prospectcampaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'normalized_email'), name='prospecting_unique_campaign_email'),
        ),
        migrations.AddConstraint(
            model_name='prospectdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('message', 'sequence'), name='prospecting_unique_attempt_sequence'),
        ),
        migrations.AddConstraint(
            model_name='prospectprovideremail',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_email_id'), name='prospecting_unique_provider_email'),
        ),
        migrations.AddConstraint(
            model_name='prospectprovideremail',
            constraint=models.UniqueConstraint(fields=('organization', 'rfc_message_id'), name='prospecting_unique_provider_rfc'),
        ),
        migrations.AddConstraint(
            model_name='prospectsequencestep',
            constraint=models.UniqueConstraint(fields=('campaign', 'step_number'), name='prospecting_unique_sequence_step'),
        ),
        migrations.AddConstraint(
            model_name='prospectsequencestepversion',
            constraint=models.UniqueConstraint(fields=('campaign_version', 'step_number'), name='prospecting_unique_step_version'),
        ),
        migrations.AddConstraint(
            model_name='prospectmessage',
            constraint=models.UniqueConstraint(fields=('recipient', 'step_version'), name='prospecting_unique_recipient_step'),
        ),
        migrations.AddConstraint(
            model_name='prospectmessage',
            constraint=models.UniqueConstraint(fields=('rfc_message_id',), name='prospecting_unique_rfc_message_id'),
        ),
        migrations.AddConstraint(
            model_name='prospectsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('organization', 'normalized_email'), name='prospecting_unique_active_suppression'),
        ),
    ]
