# Generated by Django 5.2.17 on 2026-10-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('prospecting', '0002_prospectcampaign_prospectcampaignversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel workbook')], max_length=12)),
                ('file_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('completed', 'Completed')], default='previewed', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('preview_rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_imports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_imports', to='organizations.organization')),
                ('prospect_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='prospecting.prospectlist')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
