# Generated by Django 5.2.17 on 2026-09-13 07:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_key', models.CharField(max_length=100)),
                ('trade_category', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('closed', 'Closed')], default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='outreach.invitationcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('current_status', models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled')], default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='outreach.invitationbatch')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.scopecontractorcandidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationRecipientStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='outreach.invitationrecipient')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('kind', models.CharField(choices=[('invitation', 'Invitation'), ('revision', 'Revision')], max_length=20)),
                ('from_name', models.CharField(max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='outreach.invitationrecipient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='invitationbatch',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence'), name='outreach_unique_batch_sequence'),
        ),
        migrations.AddConstraint(
            model_name='invitationrecipient',
            constraint=models.UniqueConstraint(fields=('batch', 'candidate'), name='outreach_unique_batch_candidate'),
        ),
        migrations.AddConstraint(
            model_name='outreachmessage',
            constraint=models.UniqueConstraint(fields=('recipient', 'sequence'), name='outreach_unique_message_sequence'),
        ),
    ]
