# Generated by Django 5.2.17 on 2026-09-13 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationrecipient',
            name='current_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited')], default='prepared', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationrecipientstatusevent',
            name='new_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited')], max_length=20),
        ),
        migrations.CreateModel(
            name='BatchSendApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='send_approval', to='outreach.invitationbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutreachDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('provider_key', models.CharField(max_length=40)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('safe_error_message', models.CharField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='outreach.outreachmessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'sequence'), name='outreach_unique_delivery_attempt_sequence')],
            },
        ),
    ]
