# Generated by Django 5.2.17 on 2026-09-13 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_alter_invitationrecipient_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsendapproval',
            name='message_fingerprint',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='batchsendapproval',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_approvals', to='outreach.invitationbatch'),
        ),
        migrations.AddConstraint(
            model_name='batchsendapproval',
            constraint=models.UniqueConstraint(fields=('batch', 'message_fingerprint'), name='outreach_unique_send_approval_state'),
        ),
    ]
