# Generated by Django 5.2.17 on 2026-09-13 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('outreach', '0003_batchsendapproval_message_fingerprint_and_more'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsendapproval',
            name='campaign_setup_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitationcampaign',
            name='bid_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationcampaign',
            name='questions_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationcampaign',
            name='setup_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='bid_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='campaign_setup_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='questions_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='source_scope_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion'),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='template_version',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='outreachdeliveryattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('uncertain', 'Outcome uncertain')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OutreachSenderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_sender', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSetupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bid_deadline', models.DateTimeField(blank=True, null=True)),
                ('questions_deadline', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setup_events', to='outreach.invitationcampaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'version'), name='outreach_unique_setup_version')],
            },
        ),
    ]
