# Generated by Django 5.2.17 on 2026-09-14 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('outreach', '0004_batchsendapproval_campaign_setup_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.TextField(blank=True)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL'), ('none', 'None')], default='starttls', max_length=12)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_test_status', models.CharField(blank=True, max_length=40)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_smtp', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
