# Generated by Django 5.2.17 on 2026-09-14 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('outreach', '0005_outreachsmtpconfiguration'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrecipient',
            name='delivery_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationrecipient',
            name='delivery_state',
            field=models.CharField(default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='invitationrecipient',
            name='engagement_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationrecipient',
            name='engagement_state',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='invitationrecipient',
            name='qualification_state',
            field=models.CharField(default='not_reviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='invitationrecipient',
            name='response_state',
            field=models.CharField(default='no_response', max_length=20),
        ),
        migrations.AddField(
            model_name='invitationrecipientstatusevent',
            name='source',
            field=models.CharField(default='human', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationrecipient',
            name='current_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('responded', 'Responded'), ('declined', 'Declined'), ('failed', 'Failed'), ('needs_follow_up', 'Needs follow-up')], default='prepared', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationrecipientstatusevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationrecipientstatusevent',
            name='new_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('responded', 'Responded'), ('declined', 'Declined'), ('failed', 'Failed'), ('needs_follow_up', 'Needs follow-up')], max_length=20),
        ),
        migrations.CreateModel(
            name='OutreachQualificationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_decisions', to='outreach.invitationrecipient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResendWebhookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_signing_secret', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resend_webhook', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResendWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=40)),
                ('provider_email_id', models.CharField(blank=True, max_length=120)),
                ('rfc_message_id', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.resendwebhookconfiguration')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.outreachmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationrecipient')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_email_id', models.CharField(blank=True, max_length=120)),
                ('rfc_message_id', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('references', models.CharField(blank=True, max_length=1000)),
                ('from_address', models.EmailField(blank=True, max_length=254)),
                ('to_address', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('content_status', models.CharField(default='not_applicable', max_length=20)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('channel', models.CharField(max_length=20)),
                ('outcome', models.CharField(default='responded', max_length=20)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.outreachmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationrecipient')),
                ('provider_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.resendwebhookevent')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachProviderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_email_id', models.CharField(max_length=120)),
                ('rfc_message_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.outreachmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('first_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.resendwebhookevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resendwebhookevent',
            constraint=models.UniqueConstraint(fields=('configuration', 'webhook_id'), name='outreach_unique_resend_event'),
        ),
        migrations.AddConstraint(
            model_name='outreachresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'inbound_email'), models.Q(('provider_email_id', ''), _negated=True)), fields=('organization', 'provider_email_id'), name='outreach_unique_inbound_email'),
        ),
        migrations.AddConstraint(
            model_name='outreachprovideremail',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_email_id'), name='outreach_unique_provider_email'),
        ),
        migrations.AddConstraint(
            model_name='outreachprovideremail',
            constraint=models.UniqueConstraint(fields=('organization', 'rfc_message_id'), name='outreach_unique_provider_message_id'),
        ),
    ]
