# Generated by Django 5.2.17 on 2026-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_invitationrecipient_delivery_event_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachdeliveryattempt',
            name='submitted_rfc_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
