# Generated by Django 5.2.17 on 2026-09-15 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('documents', '0005_projectdocumentselection'),
        ('organizations', '0001_initial'),
        ('outreach', '0007_outreachdeliveryattempt_submitted_rfc_message_id'),
        ('projects', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationrecipient',
            name='current_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('responded', 'Responded'), ('bid_submitted', 'Quote received'), ('declined', 'Declined'), ('failed', 'Failed'), ('needs_follow_up', 'Needs follow-up')], default='prepared', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationrecipientstatusevent',
            name='new_status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('cancelled', 'Cancelled'), ('invited', 'Invited'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('responded', 'Responded'), ('bid_submitted', 'Quote received'), ('declined', 'Declined'), ('failed', 'Failed'), ('needs_follow_up', 'Needs follow-up')], max_length=20),
        ),
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('inbound_email', 'Received by email'), ('manual_upload', 'Uploaded manually')], max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received')], default='received', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('intake_note', models.CharField(blank=True, max_length=1000)),
                ('request_key', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationbatch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationrecipient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion')),
                ('source_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.outreachresponse')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('checksum', models.CharField(max_length=64)),
                ('provider_attachment_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='documents.fileasset')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='outreach.bidsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bidsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key__isnull', False)), fields=('organization', 'request_key'), name='outreach_unique_bid_request_key'),
        ),
        migrations.AddConstraint(
            model_name='bidattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_attachment_id', ''), _negated=True), fields=('submission', 'provider_attachment_id'), name='outreach_unique_bid_provider_attachment'),
        ),
    ]
