# Generated by Django 5.2.17 on 2026-09-15 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        ('outreach', '0008_alter_invitationrecipient_current_status_and_more'),
        ('projects', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contractor_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Comparison'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('currency_review', models.CharField(choices=[('unreviewed', 'Not yet reviewed'), ('confirmed', 'Human confirmed'), ('not_stated', 'Not stated in quote')], default='unreviewed', max_length=20)),
                ('base_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('base_bid_review', models.CharField(choices=[('unreviewed', 'Not yet reviewed'), ('confirmed', 'Human confirmed'), ('not_stated', 'Not stated in quote')], default='unreviewed', max_length=20)),
                ('tax_treatment', models.CharField(choices=[('included', 'Included'), ('extra', 'Extra'), ('exempt', 'Exempt'), ('not_stated', 'Not stated / needs confirmation')], default='not_stated', max_length=20)),
                ('tax_reviewed', models.BooleanField(default=False)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_text', models.CharField(blank=True, max_length=500)),
                ('estimator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contractors.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bid_revisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.invitationrecipient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ready_bid_revisions', to=settings.AUTH_USER_MODEL)),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='outreach.bidsubmission')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='outreach.bidrevision')),
            ],
            options={
                'ordering': ('-sequence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BidCommercialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kind', models.CharField(choices=[('alternate', 'Alternate / option'), ('allowance', 'Allowance'), ('fee', 'Permit / fee / tax'), ('exclusion', 'Explicit exclusion'), ('condition', 'Qualification / condition')], max_length=20)),
                ('contractor_label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('treatment', models.CharField(blank=True, choices=[('add', 'Add'), ('deduct', 'Deduct'), ('no_cost', 'No cost'), ('price_on_request', 'Price on request'), ('included', 'Included'), ('excluded', 'Excluded'), ('extra', 'Extra'), ('allowance', 'Allowance'), ('not_stated', 'Not stated')], max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('included_in_base', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unclear', 'Unclear')], default='unclear', max_length=10)),
                ('estimator_note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopeitem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_items', to='outreach.bidrevision')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BidScopeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('included', 'Confirmed included'), ('excluded', 'Confirmed excluded'), ('qualified', 'Qualified / conditional'), ('not_addressed', 'Not addressed'), ('needs_clarification', 'Needs clarification')], default='not_addressed', max_length=30)),
                ('wording', models.TextField(blank=True)),
                ('estimator_note', models.CharField(blank=True, max_length=1000)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_coverage', to='outreach.bidrevision')),
                ('scope_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopeitem')),
            ],
        ),
        migrations.CreateModel(
            name='BidEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('quote', 'Original quote'), ('estimator', 'Estimator note'), ('contractor', 'Contractor clarification'), ('ai_suggested', 'AI suggested')], max_length=20)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidattachment')),
                ('commercial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='outreach.bidcommercialitem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='outreach.bidrevision')),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='outreach.bidscopecoverage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bidrevision',
            constraint=models.UniqueConstraint(fields=('recipient', 'sequence'), name='outreach_unique_bid_revision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='bidcommercialitem',
            constraint=models.UniqueConstraint(fields=('revision', 'sequence'), name='outreach_unique_bid_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='bidscopecoverage',
            constraint=models.UniqueConstraint(fields=('revision', 'scope_item'), name='outreach_unique_bid_scope_coverage'),
        ),
    ]
