# Generated by Django 5.2.17 on 2026-09-15 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0009_bidrevision_bidcommercialitem_bidscopecoverage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('safe_error_code', models.CharField(blank=True, max_length=60)),
                ('safe_error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidattachment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='outreach.bidsubmission')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
