# Generated by Django 5.2.17 on 2026-09-15 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_bidextractionrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidextractionrun',
            name='request_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bidextractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key__isnull', False)), fields=('submission', 'request_key'), name='outreach_unique_bid_extraction_request'),
        ),
    ]
