# Generated by Django 5.2.17 on 2026-09-15 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_bidextractionrun_request_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCandidateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_index', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('accepted', 'Accepted by human'), ('corrected', 'Corrected by human'), ('ignored', 'Ignored by human')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('commercial_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidcommercialitem')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outreach.bidevidence')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outreach.bidrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='outreach.bidextractionrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'candidate_index', 'revision'), name='outreach_unique_bid_candidate_decision')],
            },
        ),
    ]
