# Generated by Django 5.2.17 on 2026-09-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0012_bidcandidatedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrevision',
            name='commercial_items_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidrevision',
            name='scope_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
