# Generated by Django 5.2.17 on 2026-09-15 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_canonical_trade_geographic_discovery'),
        ('organizations', '0001_initial'),
        ('outreach', '0013_bidrevision_commercial_items_reviewed_and_more'),
        ('projects', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrevision',
            name='request_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bidrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key__isnull', False)), fields=('submission', 'request_key'), name='outreach_unique_bid_revision_request'),
        ),
    ]
