# Generated by Django 5.2.17 on 2026-09-16 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0003_canonical_trade_geographic_discovery"),
        ("organizations", "0001_initial"),
        ("outreach", "0014_bidrevision_request_key_and_more"),
        ("projects", "0001_initial"),
        ("scope_packages", "0005_scope_plan_fingerprint_and_coordination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BidComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready for Human Review")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bid_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="projects.project"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_bid_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scope_packages.scopepackage",
                    ),
                ),
                (
                    "scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scope_packages.scopepackageversion",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="outreach.bidcomparison",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="BidComparisonEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("revision_label", models.CharField(blank=True, max_length=120)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="contractors.company"
                    ),
                ),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="outreach.bidcomparison",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="outreach.bidrevision"
                    ),
                ),
            ],
            options={
                "ordering": ("company_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="BidLevelingAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(choices=[("add", "Add"), ("deduct", "Deduct")], max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scope_gap", "Scope gap"),
                            ("exclusion_normalization", "Exclusion normalization"),
                            ("alternate_option", "Alternate / option"),
                            ("allowance_normalization", "Allowance normalization"),
                            ("permit_fee", "Permit / fee"),
                            ("other", "Other estimator adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="outreach.bidcomparisonentry",
                    ),
                ),
                (
                    "scope_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scope_packages.scopeitem",
                    ),
                ),
                (
                    "source_commercial_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="outreach.bidcommercialitem",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="bidcomparison",
            constraint=models.UniqueConstraint(
                fields=("project", "scope_version", "sequence"),
                name="outreach_unique_comparison_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="bidcomparisonentry",
            constraint=models.UniqueConstraint(
                fields=("comparison", "revision"), name="outreach_unique_comparison_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidcomparisonentry",
            constraint=models.UniqueConstraint(
                fields=("comparison", "company"), name="outreach_unique_comparison_company"
            ),
        ),
    ]
