# Generated by Django 5.2.17 on 2026-09-17 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('outreach', '0015_bid_comparison'),
        ('projects', '0001_initial'),
        ('scope_packages', '0005_scope_plan_fingerprint_and_coordination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidHumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Human Review Finalized')], default='draft', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('selected_for_proposal', 'Selected for Proposal'), ('no_acceptable_bid', 'No Acceptable Bid')], max_length=30)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_reviews', to='outreach.bidcomparison')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bid_human_reviews', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_bid_human_reviews', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scope_packages.scopepackageversion')),
                ('selected_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_selections', to='outreach.bidcomparisonentry')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='outreach.bidhumanreview')),
            ],
            options={
                'ordering': ('-sequence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BidHumanDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('undecided', 'Undecided'), ('shortlisted', 'Shortlisted'), ('not_shortlisted', 'Not Shortlisted')], default='undecided', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_decisions', to='outreach.bidcomparisonentry')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bid_human_decisions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='outreach.bidhumanreview')),
            ],
            options={
                'ordering': ('comparison_entry__company_name', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='bidhumanreview',
            constraint=models.UniqueConstraint(fields=('comparison', 'sequence'), name='outreach_unique_human_review_sequence'),
        ),
        migrations.AddConstraint(
            model_name='bidhumandecision',
            constraint=models.UniqueConstraint(fields=('review', 'comparison_entry'), name='outreach_unique_human_decision_entry'),
        ),
    ]
