"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Building2, ExternalLink, Mail, Phone } from "lucide-react";
import { OrganizationAccessState } from "@/components/organizations/organization-access-state";
import { useOrganization } from "@/components/organizations/organization-provider";
import { Card } from "@/components/ui/card";
import { contractorsApi, type DirectoryDetail } from "@/lib/contractors";

export function SubcontractorDetail({ companyId }: { companyId: number }) {
  const { memberships, activeMembership } = useOrganization();
  const [data, setData] = useState<DirectoryDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => {
    if (!activeMembership) return;
    const controller = new AbortController();
    contractorsApi.directoryDetail(activeMembership.organization.slug, companyId, controller.signal).then(setData).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Company details could not be loaded."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [activeMembership, companyId]);
  if (!activeMembership) return <OrganizationAccessState multiple={memberships.length > 1} />;
  if (loading) return <State title="Loading company profile…" />;
  if (error || !data) return <><Link href="/subcontractors" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft className="h-4 w-4" />Back to Subcontractors</Link><div className="mt-4"><State title="Company profile unavailable" detail={error} error /></div></>;
  const { company } = data;
  return <div className="space-y-5">
    <Link href="/subcontractors" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft className="h-4 w-4" />Back to Subcontractors</Link>
    <Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">{company.source_type === "internal" ? "Internal network" : company.external_provider === "google_places" ? "Google discovered" : "Externally discovered"}</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">{company.display_name}</h1>{company.legal_name && company.legal_name !== company.display_name && <p className="text-sm text-slate-500">{company.legal_name}</p>}<p className="mt-2 text-sm text-slate-600">{[company.address, company.city, company.province, company.country].filter(Boolean).join(", ") || "Location not recorded"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${company.is_active ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{company.is_active ? "ACTIVE" : "INACTIVE"}</span></div><div className="mt-4 flex flex-wrap gap-4 text-sm">{company.phone && <span className="inline-flex items-center gap-1"><Phone className="h-4 w-4" />{company.phone}</span>}{company.email && <span className="inline-flex items-center gap-1"><Mail className="h-4 w-4" />{company.email}</span>}{company.website && <a href={company.website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-blue-700">Website<ExternalLink className="h-3.5 w-3.5" /></a>}</div></Card>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Contacts</h2><p className={`mt-2 text-sm font-semibold ${data.contact_ready ? "text-emerald-700" : "text-amber-800"}`}>{data.contact_ready ? "Contact ready" : "Missing usable contact"}</p>{data.contacts.length ? <ul className="mt-3 divide-y">{data.contacts.map((contact) => <li key={contact.id} className="py-3 text-sm"><p className="font-semibold">{contact.name}{contact.is_primary ? " · Primary" : ""}</p>{contact.title && <p className="text-slate-500">{contact.title}</p>}<p className="text-slate-600">{[contact.email, contact.phone].filter(Boolean).join(" · ") || "No contact details"}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No active contacts recorded.</p>}</Card><Card className="p-5"><h2 className="font-semibold">Trade capabilities</h2>{data.trade_capabilities.length ? <ul className="mt-3 space-y-2">{data.trade_capabilities.map((trade) => <li key={trade.id} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">{trade.trade_label}</p>{(trade.service_cities.length > 0 || trade.province) && <p className="mt-1 text-slate-500">Service area: {[...trade.service_cities, trade.province].filter(Boolean).join(", ")}</p>}{trade.keywords.length > 0 && <p className="mt-1 text-xs text-slate-500">{trade.keywords.join(" · ")}</p>}</li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No active trade capabilities recorded.</p>}</Card></section>
    <History title="Project participation" empty="No project participation recorded.">{data.project_history.map((item) => <li key={`${item.project_id}-${item.trade_key}`} className="rounded-lg border p-3 text-sm"><p className="font-semibold">{item.project_number} · {item.project_name}</p><p className="text-slate-500">{item.trade} · {label(item.candidate_status)} · Scope #{item.scope_version_id}</p>{item.history_count > 1 && <details className="mt-2 rounded-lg bg-slate-50 p-2"><summary className="cursor-pointer text-xs font-semibold text-slate-700">{item.history_count} historical participation records</summary><ul className="mt-2 space-y-1 text-xs text-slate-600">{item.history.map((record) => <li key={record.candidate_id}>Scope #{record.scope_version_id} · {label(record.candidate_status)}{record.is_current_scope ? " · Current scope" : " · Historical scope"}</li>)}</ul></details>}<div className="mt-2 flex flex-wrap gap-3"><ProjectLink projectId={item.project_id} section="contractors" label="Contractors" /><ProjectLink projectId={item.project_id} section="outreach" label="Outreach" /><ProjectLink projectId={item.project_id} section="bids" label="Bids" /><ProjectLink projectId={item.project_id} section="comparisons" label="Comparisons" /></div></li>)}</History>
    <History title="Outreach history" empty="No outreach participation recorded.">{data.outreach_history.map((item) => <li key={item.recipient_id} className="rounded-lg border p-3 text-sm"><p className="font-semibold">{item.project_name} · {item.trade}</p><p className="text-slate-500">Invitation: {label(item.invitation_state)} · Response: {label(item.response_state)} · Qualification for this invitation: {label(item.qualification_state)}</p><ProjectLink projectId={item.project_id} section="outreach" label="Open exact project Outreach" /></li>)}</History>
    <History title="Bid history" empty="No quote submissions recorded.">{data.bid_history.map((item) => <li key={item.submission_id} className="rounded-lg border p-3 text-sm"><p className="font-semibold">{item.project_name} · {item.trade}</p><p className="text-slate-500">Quote received · Structured bid: {label(item.structured_status)} · {new Date(item.received_at).toLocaleDateString()}</p><ProjectLink projectId={item.project_id} section="bids" label="Open project Bids" /></li>)}</History>
    <p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">{data.history_note}</p>
  </div>;
}

function History({ title, empty, children }: { title: string; empty: string; children: React.ReactNode[] }) { return <Card className="p-5"><h2 className="font-semibold">{title}</h2>{children.length ? <ul className="mt-3 grid gap-3 lg:grid-cols-2">{children}</ul> : <p className="mt-3 text-sm text-slate-500">{empty}</p>}</Card>; }
function ProjectLink({ projectId, section, label: text }: { projectId: number; section: string; label: string }) { return <Link href={`/projects/${projectId}/${section}`} className="mt-2 inline-block font-semibold text-blue-700">{text}</Link>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function State({ title, detail, error = false }: { title: string; detail?: string; error?: boolean }) { return <Card className={`flex min-h-56 flex-col items-center justify-center p-8 text-center ${error ? "border-red-200" : ""}`}><Building2 className="h-8 w-8 text-slate-400" /><h1 className="mt-3 font-semibold">{title}</h1>{detail && <p className="mt-1 max-w-xl text-sm text-slate-500">{detail}</p>}</Card>; }
