"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, FileText, Search } from "lucide-react";
import { OrganizationAccessState } from "@/components/organizations/organization-access-state";
import { useOrganization } from "@/components/organizations/organization-provider";
import { Card } from "@/components/ui/card";
import { procurementDirectoriesApi, type ProposalDirectoryResponse } from "@/lib/procurement-directories";

export function ProposalDirectory() {
  const { memberships, activeMembership } = useOrganization();
  const [search, setSearch] = useState(""); const [filters, setFilters] = useState({ search: "", status: "", award_status: "" }); const [page, setPage] = useState(1);
  const [data, setData] = useState<ProposalDirectoryResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); setError(""); setFilters((value) => ({ ...value, search })); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { if (!activeMembership) return; const controller = new AbortController(); const query = new URLSearchParams({ page: String(page), page_size: "25" }); Object.entries(filters).forEach(([key, value]) => value && query.set(key, value)); procurementDirectoriesApi.proposals(activeMembership.organization.slug, query, controller.signal).then(setData).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Proposals could not be loaded."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [activeMembership, filters, page]);
  if (!activeMembership) return <OrganizationAccessState multiple={memberships.length > 1} />;
  const change = (key: "status" | "award_status", value: string) => { setLoading(true); setError(""); setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const filtered = Object.values(filters).some(Boolean);
  return <div className="space-y-5"><header><h1 className="text-2xl font-semibold">Client Proposals</h1><p className="mt-1 text-sm text-slate-500">Client-facing proposal versions and award state, without internal procurement pricing.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total Proposals" value={data?.summary.total} /><Metric label="Draft" value={data?.summary.draft} /><Metric label="Finalized" value={data?.summary.finalized} /><Metric label="Awarded" value={data?.summary.awarded} /></section>
    <Card><div className="grid gap-3 border-b p-4 md:grid-cols-3"><label className="relative"><span className="sr-only">Search proposals</span><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search project, client or proposal" className="h-10 w-full rounded-lg border pl-9 pr-3" /></label><Select label="Proposal status" value={filters.status} options={(data?.filters.statuses ?? []).map((item) => [item.value, item.label])} onChange={(value) => change("status", value)} /><Select label="Award status" value={filters.award_status} options={(data?.filters.award_statuses ?? []).map((item) => [item.value, item.label])} onChange={(value) => change("award_status", value)} /></div>
      {error ? <State title="Proposals unavailable" detail={error} /> : loading && !data ? <State title="Loading client proposals…" /> : !data?.results.length ? <State title={filtered ? "No proposals match these filters" : "No client proposals yet"} /> : <><div className={`overflow-x-auto ${loading ? "opacity-60" : ""}`}><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Project", "Client", "Proposal", "Version", "Estimate", "Proposed Amount", "PDF", "Award State", "Issue Date", "Action"].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{data.results.map((item) => <tr key={item.id}><td className="px-4 py-3"><strong>{item.project_number}</strong><p className="text-xs text-slate-500">{item.project_name}</p></td><td className="px-4 py-3">{item.client_name || "Not recorded"}</td><td className="px-4 py-3">{item.proposal_number || `Proposal #${item.id}`}<p className="text-xs capitalize text-slate-500">{item.status}</p></td><td className="px-4 py-3">{item.version ? `V${item.version}` : "Not started"}</td><td className="px-4 py-3">{item.estimate_version ? `Estimate V${item.estimate_version}` : "Not bound"}</td><td className="px-4 py-3 font-semibold">{item.proposed_amount && item.currency ? `${item.currency} ${formatAmount(item.proposed_amount)}` : "Not available"}</td><td className="px-4 py-3">{item.pdf_available ? "Available" : "Not generated"}</td><td className="px-4 py-3 capitalize">{item.award_status.replaceAll("_", " ")}</td><td className="px-4 py-3">{item.issue_date ? new Date(`${item.issue_date}T00:00:00`).toLocaleDateString() : "Not issued"}</td><td className="px-4 py-3"><Link href={item.project_url} className="font-semibold text-blue-700 hover:underline">Open Proposal</Link></td></tr>)}</tbody></table></div><Pager data={data} loading={loading} setPage={(update) => { setLoading(true); setError(""); setPage(update); }} /></>}
    </Card></div>;
}
function Metric({ label, value }: { label: string; value?: number }) { return <Card className="bg-emerald-50 p-4 text-emerald-900"><p className="text-2xl font-semibold">{value ?? "—"}</p><p className="text-xs font-medium">{label}</p></Card>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-lg border bg-white px-3"><option value="">All {label.toLowerCase()}</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select>; }
function State({ title, detail }: { title: string; detail?: string }) { return <div className="flex min-h-56 flex-col items-center justify-center p-8 text-center"><FileText className="h-8 w-8 text-slate-400" /><h2 className="mt-3 font-semibold">{title}</h2>{detail && <p className="mt-1 text-sm text-slate-500">{detail}</p>}</div>; }
function Pager({ data, loading, setPage }: { data: ProposalDirectoryResponse; loading: boolean; setPage: React.Dispatch<React.SetStateAction<number>> }) { return <div className="flex items-center justify-between border-t px-4 py-3 text-sm"><span>Page {data.page} · {data.count} proposals</span><div className="flex gap-2"><button aria-label="Previous page" disabled={!data.previous || loading} onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><button aria-label="Next page" disabled={!data.next || loading} onClick={() => setPage((value) => value + 1)} className="rounded border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>; }
function formatAmount(value: string) { const [whole, fraction = "00"] = value.split("."); return `${whole.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${fraction.padEnd(2, "0").slice(0, 2)}`; }
