# Generated by Django 5.2.17 on 2026-09-06 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0004_alter_projectintelligencesnapshotentry_decision_and_more'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_key', models.SlugField(max_length=100)),
                ('trade_category', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scope_packages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_packages', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_packages', to='projects.project')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_packages', to='analysis.projectintelligencesnapshot')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_scope_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('trade_category', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ScopePackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('clarifications', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scope_package_versions', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='scope_packages.scopepackage')),
            ],
            options={
                'ordering': ('-version', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ScopePackageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_package_sources', to='analysis.projectintelligencesnapshotentry')),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='scope_packages.scopepackageversion')),
            ],
            options={
                'ordering': ('package_version_id', 'snapshot_entry_id'),
            },
        ),
        migrations.AddField(
            model_name='scopepackage',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_package', to='scope_packages.scopepackageversion'),
        ),
        migrations.AddConstraint(
            model_name='scopepackageversion',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='scope_unique_package_version'),
        ),
        migrations.AddConstraint(
            model_name='scopepackagesource',
            constraint=models.UniqueConstraint(fields=('package_version', 'snapshot_entry'), name='scope_unique_version_snapshot_entry'),
        ),
        migrations.AddConstraint(
            model_name='scopepackage',
            constraint=models.UniqueConstraint(fields=('project', 'source_snapshot', 'trade_key'), name='scope_unique_project_snapshot_trade'),
        ),
    ]
