# Generated by Django 5.2.17 on 2026-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopepackage',
            name='generation_rule_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scopepackage',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
    ]
