# Generated by Django 5.2.17 on 2026-09-08 22:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_projectintelligencesnapshotentry_decision_and_more'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('scope_packages', '0002_scopepackage_generation_rule_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.SlugField(max_length=160)),
                ('item_type', models.CharField(choices=[('demolition', 'Demolition'), ('supply_install', 'Supply / install'), ('controls', 'Controls'), ('testing', 'Testing'), ('permits', 'Permits'), ('coordination', 'Coordination'), ('submittals', 'Submittals'), ('closeout', 'Closeout'), ('equipment', 'Equipment-specific work'), ('general', 'General requirement')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ScopeItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('scope_item_id', 'snapshot_provenance_id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='scopepackage',
            name='scope_unique_project_snapshot_trade',
        ),
        migrations.AddConstraint(
            model_name='scopepackage',
            constraint=models.UniqueConstraint(fields=('project', 'source_snapshot', 'trade_key', 'generation_rule_version'), name='scope_unique_project_snapshot_trade'),
        ),
        migrations.AddField(
            model_name='scopeitem',
            name='package_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_items', to='scope_packages.scopepackageversion'),
        ),
        migrations.AddField(
            model_name='scopeitemsource',
            name='scope_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='scope_packages.scopeitem'),
        ),
        migrations.AddField(
            model_name='scopeitemsource',
            name='snapshot_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_item_sources', to='analysis.projectintelligencesnapshotentry'),
        ),
        migrations.AddField(
            model_name='scopeitemsource',
            name='snapshot_provenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_item_sources', to='analysis.projectintelligencesnapshotprovenance'),
        ),
        migrations.AddConstraint(
            model_name='scopeitem',
            constraint=models.UniqueConstraint(fields=('package_version', 'item_key'), name='scope_unique_item_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='scopeitem',
            constraint=models.UniqueConstraint(fields=('package_version', 'sequence'), name='scope_unique_item_sequence_per_version'),
        ),
        migrations.AddConstraint(
            model_name='scopeitemsource',
            constraint=models.UniqueConstraint(fields=('scope_item', 'snapshot_provenance'), name='scope_unique_item_snapshot_provenance'),
        ),
    ]
