# Generated by Django 5.2.17 on 2026-09-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_packages', '0003_scopeitem_scopeitemsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeitem',
            name='responsibility',
            field=models.CharField(choices=[('supply_install', 'Supply & Install'), ('install_only', 'Install Only'), ('owner_supplied', 'Owner Supplied'), ('landlord_supplied', 'Landlord Supplied'), ('existing_to_remain', 'Existing to Remain'), ('relocate_reuse', 'Relocate-Reuse'), ('by_others', 'By Others'), ('unclear', 'Unclear')], default='unclear', max_length=30),
        ),
    ]
