# Generated by Django 5.2.17 on 2026-09-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('scope_packages', '0002_scopepackage_generation_rule_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Canada', max_length=80)),
                ('source_type', models.CharField(choices=[('internal', 'Internal'), ('discovered', 'External')], default='internal', max_length=20)),
                ('external_provider', models.CharField(blank=True, max_length=50)),
                ('external_place_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contractors.company')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_key', models.CharField(choices=[('hvac-mechanical', 'HVAC / Mechanical'), ('plumbing', 'Plumbing'), ('fire-protection', 'Fire Protection / Sprinkler'), ('general-requirements', 'General Requirements')], max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=80)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('search_terms', models.JSONField(default=list)),
                ('provider', models.CharField(max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_discovery_requests', to=settings.AUTH_USER_MODEL)),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_requests', to='scope_packages.scopepackage')),
                ('scope_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_requests', to='scope_packages.scopepackageversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeContractorCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('shortlisted', 'Shortlisted'), ('approved_for_outreach', 'Approved for outreach'), ('rejected', 'Rejected')], default='candidate', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_candidates', to='contractors.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contractor_candidates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_candidates', to='projects.project')),
                ('scope_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_candidates', to='scope_packages.scopepackage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_contractor_candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_key', models.CharField(choices=[('hvac-mechanical', 'HVAC / Mechanical'), ('plumbing', 'Plumbing'), ('fire-protection', 'Fire Protection / Sprinkler'), ('general-requirements', 'General Requirements')], max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('service_cities', models.JSONField(blank=True, default=list)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('internal', 'Internal'), ('discovered', 'External')], default='internal', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_capabilities', to='contractors.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('external_place_id', ''), _negated=True), fields=('organization', 'external_provider', 'external_place_id'), name='contractor_unique_external_place'),
        ),
        migrations.AddConstraint(
            model_name='scopecontractorcandidate',
            constraint=models.UniqueConstraint(fields=('project', 'scope_package', 'company'), name='contractor_unique_scope_company'),
        ),
        migrations.AddConstraint(
            model_name='tradecapability',
            constraint=models.UniqueConstraint(fields=('company', 'trade_key'), name='contractor_unique_company_trade'),
        ),
    ]
