# Generated by Django 5.2.17 on 2026-09-02 16:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('source_verification', 'Source verification')], default='source_verification', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, choices=[('source_missing', 'Source missing'), ('storage_unavailable', 'Storage unavailable'), ('size_mismatch', 'Size mismatch'), ('checksum_mismatch', 'Checksum mismatch'), ('processing_error', 'Processing error'), ('worker_lost', 'Worker lost')], max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='documents.documentrevision')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'last_dispatched_at'], name='processing__status_2d5c3e_idx'), models.Index(fields=['status', 'lease_expires_at'], name='processing__status_039942_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('document_revision', 'job_type'), name='processing_unique_active_revision_job')],
            },
        ),
    ]
