# Generated by Django 5.2.17 on 2026-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processingjob_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='error_code',
            field=models.CharField(blank=True, choices=[('source_missing', 'Source missing'), ('storage_unavailable', 'Storage unavailable'), ('size_mismatch', 'Size mismatch'), ('checksum_mismatch', 'Checksum mismatch'), ('processing_error', 'Processing error'), ('worker_lost', 'Worker lost'), ('source_not_verified', 'Source not verified'), ('not_pdf', 'Not a PDF'), ('pdf_encrypted', 'PDF encrypted'), ('pdf_corrupt', 'PDF corrupt'), ('indexing_error', 'Indexing error'), ('not_presentation', 'Not a presentation'), ('presentation_corrupt', 'Presentation corrupt')], max_length=40),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('source_verification', 'Source verification'), ('pdf_indexing', 'PDF indexing'), ('presentation_indexing', 'Presentation indexing')], default='source_verification', max_length=40),
        ),
    ]
