from django.urls import path

from .views import (
    BatchCreateView,
    BatchDeliveryView,
    BidAttachmentDownloadView,
    BidSubmissionListView,
    CampaignCreateView,
    CampaignRFQPreviewView,
    CampaignSetupView,
    InboundBidImportView,
    MessageRetryView,
    OutreachSenderSettingsView,
    OutreachSMTPConnectionTestView,
    OutreachSMTPSettingsView,
    OutreachSMTPTestEmailView,
    OutreachWorkspaceView,
    RecipientCreateView,
    RecipientQualificationView,
    RecipientResponseView,
    ResendWebhookSettingsView,
    ResendWebhookView,
    UnassignedResponsesView,
)

urlpatterns = [
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/bid-submissions/",
        BidSubmissionListView.as_view(),
        name="bid-submission-list",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/inbound-responses/<int:response_pk>/import-quote/",
        InboundBidImportView.as_view(),
        name="inbound-bid-import",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/bid-submissions/<int:submission_pk>/attachments/<int:attachment_pk>/download/",
        BidAttachmentDownloadView.as_view(),
        name="bid-attachment-download",
    ),
    path(
        "webhooks/resend/<uuid:endpoint_token>/",
        ResendWebhookView.as_view(),
        name="resend-webhook",
    ),
    path(
        "organizations/<slug:organization_slug>/resend-webhook-settings/",
        ResendWebhookSettingsView.as_view(),
        name="resend-webhook-settings",
    ),
    path(
        "organizations/<slug:organization_slug>/outreach-unassigned-responses/",
        UnassignedResponsesView.as_view(),
        name="outreach-unassigned-responses",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-recipients/<int:recipient_pk>/response/",
        RecipientResponseView.as_view(),
        name="outreach-recipient-response",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-recipients/<int:recipient_pk>/qualification/",
        RecipientQualificationView.as_view(),
        name="outreach-recipient-qualification",
    ),
    path(
        "organizations/<slug:organization_slug>/outreach-smtp/",
        OutreachSMTPSettingsView.as_view(),
        name="outreach-smtp-settings",
    ),
    path(
        "organizations/<slug:organization_slug>/outreach-smtp/test-connection/",
        OutreachSMTPConnectionTestView.as_view(),
        name="outreach-smtp-test-connection",
    ),
    path(
        "organizations/<slug:organization_slug>/outreach-smtp/test-email/",
        OutreachSMTPTestEmailView.as_view(),
        name="outreach-smtp-test-email",
    ),
    path(
        "organizations/<slug:organization_slug>/outreach-sender/",
        OutreachSenderSettingsView.as_view(),
        name="outreach-sender-settings",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-campaigns/<int:campaign_pk>/setup/",
        CampaignSetupView.as_view(),
        name="outreach-campaign-setup",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-batches/<int:batch_pk>/delivery/<str:action>/",
        BatchDeliveryView.as_view(),
        name="outreach-batch-delivery",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-messages/<int:message_pk>/retry/",
        MessageRetryView.as_view(),
        name="outreach-message-retry",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach/",
        OutreachWorkspaceView.as_view(),
        name="outreach-workspace",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-campaigns/",
        CampaignCreateView.as_view(),
        name="outreach-campaign-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-campaigns/<int:campaign_pk>/batches/",
        BatchCreateView.as_view(),
        name="outreach-batch-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-batches/<int:batch_pk>/recipients/",
        RecipientCreateView.as_view(),
        name="outreach-recipient-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/outreach-campaigns/<int:campaign_pk>/rfq-preview/",
        CampaignRFQPreviewView.as_view(),
        name="outreach-campaign-rfq-preview",
    ),
]
