# Generated by Django 5.2.17 on 2026-09-01 14:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('drawings', 'Drawings'), ('specifications', 'Specifications'), ('addendum', 'Addendum'), ('client_scope', 'Client scope'), ('landlord_requirements', 'Landlord requirements'), ('responsibility_schedule', 'Responsibility schedule'), ('bid_requirements', 'Bid requirements / form'), ('schedule', 'Schedule'), ('spreadsheet', 'Spreadsheet'), ('image_reference', 'Image / reference'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('discipline', models.CharField(blank=True, choices=[('general', 'General'), ('architectural', 'Architectural'), ('structural', 'Structural'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('fire_protection', 'Fire protection'), ('interiors', 'Interiors'), ('landscape', 'Landscape'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_label', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_filename', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.document')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='documents.documentrevision')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_documents', to='documents.documentrevision'),
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_backend', models.CharField(choices=[('s3', 'S3-compatible object storage')], default='s3', max_length=20)),
                ('bucket', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('declared_mime_type', models.CharField(blank=True, max_length=255)),
                ('detected_mime_type', models.CharField(blank=True, max_length=255)),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('checksum_algorithm', models.CharField(choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512')], default='sha256', max_length=20)),
                ('checksum', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_file_assets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_assets', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_files', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_file', to='documents.fileasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_files', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='project_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document_revision', to='documents.projectfile'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['organization', 'checksum_algorithm', 'checksum'], name='documents_f_organiz_3d5b3c_idx'),
        ),
    ]
