# Generated by Django 5.2.17 on 2026-09-02 18:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('page_label', models.CharField(blank=True, max_length=100)),
                ('width_points', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height_points', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rotation_degrees', models.PositiveSmallIntegerField(choices=[(0, '0 degrees'), (90, '90 degrees'), (180, '180 degrees'), (270, '270 degrees')], default=0)),
                ('native_text', models.TextField(blank=True)),
                ('native_text_char_count', models.PositiveIntegerField(default=0)),
                ('has_native_text', models.BooleanField(default=False)),
                ('parser_name', models.CharField(max_length=100)),
                ('parser_version', models.CharField(max_length=100)),
                ('indexed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='documents.documentrevision')),
            ],
            options={
                'ordering': ('document_revision_id', 'page_number'),
            },
        ),
        migrations.CreateModel(
            name='DrawingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_number', models.CharField(blank=True, max_length=50)),
                ('sheet_title', models.CharField(blank=True, max_length=255)),
                ('extraction_method', models.CharField(choices=[('page_label', 'PDF page label'), ('native_text', 'Native PDF text')], max_length=30)),
                ('quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='drawing_sheet', to='documents.documentpage')),
            ],
            options={
                'ordering': ('page__document_revision_id', 'page__page_number'),
            },
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['document_revision', 'page_number'], name='documents_d_documen_1e9a0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document_revision', 'page_number'), name='documents_unique_revision_page_number'),
        ),
    ]
