# Generated by Django 5.2.17 on 2026-09-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentpage_drawingsheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='page_label',
            field=models.TextField(blank=True),
        ),
    ]
