# Generated by Django 5.2.17 on 2026-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentpage_page_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('drawings', 'Drawings'), ('specifications', 'Specifications'), ('addendum', 'Addendum'), ('client_scope', 'Client scope'), ('landlord_requirements', 'Landlord requirements'), ('responsibility_schedule', 'Responsibility schedule'), ('bid_requirements', 'Bid requirements / form'), ('schedule', 'Schedule'), ('spreadsheet', 'Spreadsheet'), ('image_reference', 'Image / reference'), ('narrative', 'Narrative'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='discipline',
            field=models.CharField(blank=True, choices=[('general', 'General / Multi-discipline'), ('architectural', 'Architectural'), ('structural', 'Structural'), ('civil', 'Civil / Site'), ('mechanical', 'Mechanical'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('fire_protection', 'Fire Protection / Sprinkler'), ('low_voltage', 'Low Voltage / Data'), ('security', 'Security'), ('av', 'AV'), ('signage', 'Signage'), ('roofing', 'Roofing'), ('interiors', 'Interiors'), ('landscape', 'Landscape'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=40),
        ),
    ]
