# Generated by Django 5.2.17 on 2026-09-10 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_category_alter_document_discipline'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estimating_selection', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_set_selections', to='projects.project')),
                ('selected_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimating_set_selections', to='documents.documentrevision')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_project_document_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('document__category', 'document__discipline', 'document__title'),
            },
        ),
    ]
