# Generated by Django 5.2.17 on 2026-09-02 22:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_documentpage_page_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('prompt_version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=80)),
                ('analysis_version', models.CharField(max_length=80)),
                ('input_manifest', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('usage_metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_attempt_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, choices=[('source_not_verified', 'Source not verified'), ('pdf_not_indexed', 'PDF not indexed'), ('unsupported_document', 'Unsupported document'), ('ai_configuration_missing', 'AI configuration missing'), ('provider_unavailable', 'Provider unavailable'), ('provider_rate_limited', 'Provider rate limited'), ('provider_timeout', 'Provider timeout'), ('invalid_structured_response', 'Invalid structured response'), ('page_render_failed', 'Page render failed'), ('analysis_failed', 'Analysis failed'), ('worker_lost', 'Worker lost')], max_length=50)),
                ('safe_failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='documents.documentrevision')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='analysis.analysisrun')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AnalysisTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('page_analysis', 'Page analysis'), ('document_synthesis', 'Document synthesis')], max_length=40)),
                ('input_mode', models.CharField(choices=[('native_text', 'Native text'), ('native_text_vision', 'Native text and vision'), ('vision', 'Vision'), ('structured_page_results', 'Structured page results')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('prompt_version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=80)),
                ('input_metadata', models.JSONField(default=dict)),
                ('structured_result', models.JSONField(blank=True, default=dict)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('usage_metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, choices=[('source_not_verified', 'Source not verified'), ('pdf_not_indexed', 'PDF not indexed'), ('unsupported_document', 'Unsupported document'), ('ai_configuration_missing', 'AI configuration missing'), ('provider_unavailable', 'Provider unavailable'), ('provider_rate_limited', 'Provider rate limited'), ('provider_timeout', 'Provider timeout'), ('invalid_structured_response', 'Invalid structured response'), ('page_render_failed', 'Page render failed'), ('analysis_failed', 'Analysis failed'), ('worker_lost', 'Worker lost')], max_length=50)),
                ('safe_error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='analysis.analysisrun')),
                ('document_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_task_runs', to='documents.documentpage')),
            ],
            options={
                'ordering': ('analysis_run_id', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='analysis_an_status_1bf44c_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('document_revision',), name='analysis_unique_active_revision_run'),
        ),
        migrations.AddConstraint(
            model_name='analysistaskrun',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'document_page', 'task_type'), name='analysis_unique_page_task_per_run'),
        ),
        migrations.AddConstraint(
            model_name='analysistaskrun',
            constraint=models.UniqueConstraint(condition=models.Q(('document_page__isnull', True)), fields=('analysis_run', 'task_type'), name='analysis_unique_document_task_per_run'),
        ),
    ]
