# Generated by Django 5.2.17 on 2026-09-03 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('documents', '0003_alter_documentpage_page_label'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_candidate_key', models.CharField(max_length=64)),
                ('semantic_key', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('project_fact', 'Project fact'), ('date_deadline', 'Date / deadline'), ('bid_condition', 'Bid condition'), ('scope_trade', 'Scope / trade'), ('responsibility', 'Responsibility'), ('permit_inspection', 'Permit / inspection'), ('landlord_requirement', 'Landlord requirement'), ('owner_third_party_item', 'Owner / third-party item'), ('commercial', 'Commercial condition'), ('submittal_closeout', 'Submittal / closeout'), ('open_question', 'Open question')], max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('machine_value', models.TextField(max_length=2000)),
                ('normalized_machine_value', models.CharField(max_length=2000)),
                ('machine_support', models.CharField(choices=[('explicit', 'Explicit'), ('strongly_supported', 'Strongly supported'), ('inferred', 'Inferred'), ('uncertain', 'Uncertain')], max_length=30)),
                ('schema_version', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='analysis.analysisrun')),
                ('analysis_task_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='analysis.analysistaskrun')),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_findings', to='documents.documentrevision')),
            ],
            options={
                'ordering': ('analysis_run_id', 'category', 'subject', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FindingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('edited_accepted', 'Edited / Accepted'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], max_length=30)),
                ('reviewed_value', models.TextField(blank=True, max_length=2000)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='analysis.extractedfinding')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_reviews', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='analysis.findingreview')),
            ],
            options={
                'ordering': ('finding_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FindingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64)),
                ('relation', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('qualifies', 'Qualifies')], default='supports', max_length=20)),
                ('evidence_mode', models.CharField(choices=[('native_text', 'Native text'), ('visual', 'Visual'), ('page_label', 'Page label'), ('other', 'Other')], max_length=20)),
                ('evidence_excerpt', models.CharField(blank=True, max_length=500)),
                ('visual_evidence_description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_task_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_sources', to='analysis.analysistaskrun')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_sources', to='documents.documentpage')),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_sources', to='documents.documentrevision')),
                ('drawing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finding_sources', to='documents.drawingsheet')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='analysis.extractedfinding')),
            ],
            options={
                'ordering': ('finding_id', 'document_page__page_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IntelligenceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_key', models.CharField(max_length=255)),
                ('participant_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('conflict_type', models.CharField(default='value_mismatch', max_length=40)),
                ('explanation', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_note', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_conflicts', to='analysis.analysisrun')),
                ('findings', models.ManyToManyField(related_name='conflicts', to='analysis.extractedfinding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_conflicts', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_intelligence_conflicts', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='analysis.intelligenceconflict')),
            ],
            options={
                'ordering': ('status', 'semantic_key', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='extractedfinding',
            index=models.Index(fields=['analysis_run', 'semantic_key'], name='analysis_ex_analysi_999ec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedfinding',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'source_candidate_key'), name='analysis_unique_candidate_per_run'),
        ),
        migrations.AddConstraint(
            model_name='findingsource',
            constraint=models.UniqueConstraint(fields=('finding', 'source_key'), name='analysis_unique_source_per_finding'),
        ),
        migrations.AddConstraint(
            model_name='intelligenceconflict',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'participant_key', 'version'), name='analysis_unique_conflict_version'),
        ),
    ]
