# Generated by Django 5.2.17 on 2026-09-03 11:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_extractedfinding_findingreview_findingsource_and_more'),
        ('documents', '0003_alter_documentpage_page_label'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntelligenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fingerprint', models.CharField(max_length=64)),
                ('schema_version', models.CharField(default='project-intelligence-v1', max_length=80)),
                ('manifest', models.JSONField(default=dict)),
                ('summary_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_intelligence_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ('-version', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectIntelligenceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_note', models.CharField(blank=True, max_length=1000)),
                ('readiness_result', models.JSONField(default=dict)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_approvals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_approvals', to='projects.project')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='analysis.projectintelligencesnapshot')),
            ],
            options={
                'ordering': ('-approved_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectIntelligenceSnapshotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('edited_accepted', 'Edited / Accepted'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], max_length=30)),
                ('effective_value', models.TextField(blank=True, max_length=2000)),
                ('semantic_key', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('project_fact', 'Project fact'), ('date_deadline', 'Date / deadline'), ('bid_condition', 'Bid condition'), ('scope_trade', 'Scope / trade'), ('responsibility', 'Responsibility'), ('permit_inspection', 'Permit / inspection'), ('landlord_requirement', 'Landlord requirement'), ('owner_third_party_item', 'Owner / third-party item'), ('commercial', 'Commercial condition'), ('submittal_closeout', 'Submittal / closeout'), ('open_question', 'Open question')], max_length=40)),
                ('included_in_intelligence', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_entries', to='analysis.extractedfinding')),
                ('finding_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_entries', to='analysis.findingreview')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='analysis.projectintelligencesnapshot')),
            ],
            options={
                'ordering': ('snapshot_id', 'category', 'semantic_key', 'finding_id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectIntelligenceSnapshotProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_task_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.analysistaskrun')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentpage')),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentrevision')),
                ('drawing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.drawingsheet')),
                ('finding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_provenance', to='analysis.findingsource')),
                ('snapshot_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenance', to='analysis.projectintelligencesnapshotentry')),
            ],
            options={
                'ordering': ('snapshot_entry_id', 'document_page_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectIntelligenceSnapshotSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_sources', to='analysis.analysisrun')),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_sources', to='documents.documentrevision')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='analysis.projectintelligencesnapshot')),
            ],
            options={
                'ordering': ('snapshot_id', 'analysis_run_id'),
            },
        ),
        migrations.AddField(
            model_name='projectintelligencesnapshotentry',
            name='snapshot_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='analysis.projectintelligencesnapshotsource'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='analysis_unique_snapshot_version'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='analysis_unique_snapshot_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshotprovenance',
            constraint=models.UniqueConstraint(fields=('snapshot_entry', 'finding_source'), name='analysis_unique_snapshot_entry_source'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshotsource',
            constraint=models.UniqueConstraint(fields=('snapshot', 'analysis_run'), name='analysis_unique_snapshot_run'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshotsource',
            constraint=models.UniqueConstraint(fields=('snapshot', 'document_revision'), name='analysis_unique_snapshot_revision'),
        ),
        migrations.AddConstraint(
            model_name='projectintelligencesnapshotentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'finding'), name='analysis_unique_snapshot_finding'),
        ),
    ]
