# Generated by Django 5.2.17 on 2026-09-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_projectintelligencesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectintelligencesnapshotentry',
            name='decision',
            field=models.CharField(choices=[('machine_handled', 'AI handled'), ('accepted', 'Accepted'), ('edited_accepted', 'Edited / Accepted'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectintelligencesnapshotentry',
            name='finding_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_snapshot_entries', to='analysis.findingreview'),
        ),
    ]
