# Generated by Django 5.2.17 on 2026-09-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_cancellation_and_task_reuse'),
        ('documents', '0005_projectdocumentselection'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisrun',
            name='analysis_unique_active_revision_run',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='project_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_set_analysis_runs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='run_kind',
            field=models.CharField(choices=[('document', 'Document review'), ('project_set', 'Project document-set review')], default='document', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('run_kind', 'document'), ('status__in', ('queued', 'running'))), fields=('document_revision',), name='analysis_unique_active_revision_run'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('run_kind', 'project_set'), ('status__in', ('queued', 'running'))), fields=('project_context',), name='analysis_unique_active_project_set_run'),
        ),
    ]
