from django.urls import path

from .views import (
    AwardedProjectsView,
    EstimateAssemblyView,
    EstimateCommercialView,
    EstimateCreateView,
    EstimateVersionCreateView,
    ProjectAwardConfirmView,
    ProjectAwardCreateView,
    ProjectAwardTransitionView,
    ProposalCreateView,
    ProposalFinalizeView,
    ProposalPdfDownloadView,
    ProposalPdfGenerateView,
    ProposalVersionContentView,
    ProposalVersionCreateView,
    ProposalWorkspaceView,
    TradeAwardConfirmView,
    TradeAwardCreateView,
)

urlpatterns = [
    path(
        "organizations/<slug:organization_slug>/awarded-projects/",
        AwardedProjectsView.as_view(),
        name="awarded-projects",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposal-workspace/",
        ProposalWorkspaceView.as_view(),
        name="proposal-workspace",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/estimates/",
        EstimateCreateView.as_view(),
        name="estimate-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/estimates/<int:estimate_pk>/versions/",
        EstimateVersionCreateView.as_view(),
        name="estimate-version-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/estimate-versions/<int:version_pk>/assemble/",
        EstimateAssemblyView.as_view(),
        name="estimate-version-assemble",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/estimate-versions/<int:version_pk>/<str:kind>/",
        EstimateCommercialView.as_view(),
        name="estimate-commercial-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/estimate-versions/<int:version_pk>/<str:kind>/<int:item_pk>/",
        EstimateCommercialView.as_view(),
        name="estimate-commercial-detail",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposals/",
        ProposalCreateView.as_view(),
        name="proposal-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposals/<int:proposal_pk>/versions/",
        ProposalVersionCreateView.as_view(),
        name="proposal-version-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposal-versions/<int:version_pk>/content/",
        ProposalVersionContentView.as_view(),
        name="proposal-version-content",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposal-versions/<int:version_pk>/finalize/",
        ProposalFinalizeView.as_view(),
        name="proposal-version-finalize",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposal-versions/<int:version_pk>/pdf/",
        ProposalPdfGenerateView.as_view(),
        name="proposal-pdf-generate",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/proposal-pdfs/<int:artifact_pk>/download/",
        ProposalPdfDownloadView.as_view(),
        name="proposal-pdf-download",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/project-awards/",
        ProjectAwardCreateView.as_view(),
        name="project-award-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/project-awards/<int:award_pk>/confirm/",
        ProjectAwardConfirmView.as_view(),
        name="project-award-confirm",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/project-awards/<int:award_pk>/transition/",
        ProjectAwardTransitionView.as_view(),
        name="project-award-transition",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/trade-awards/",
        TradeAwardCreateView.as_view(),
        name="trade-award-create",
    ),
    path(
        "organizations/<slug:organization_slug>/projects/<int:project_pk>/trade-awards/<int:award_pk>/confirm/",
        TradeAwardConfirmView.as_view(),
        name="trade-award-confirm",
    ),
]
